name: flutter_zig_bridge_example
description: Demo app for flutter_zig_bridge
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_zig_bridge:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  meta: ^1.18.1
